### ISSUE TITLE
Schema for IVR

### ISSUE THREAD

**Issue by murugan-pandian** [zeflq/fs_curl_mongo#1]
where i can find MNGOJS schema for IVR

**Comment by zeflq** [comment]
u have to add it by your self it is almost like the dialplan/dialplan_details shema. see <strong>Add new module</strong> section to add a new module

**Comment by murugan-pandian** [comment]
where i can find <b>Add NEW MODULE</b> section

**Comment by zeflq** [comment]
README ;)

**Comment by murugan-pandian** [comment]
Thanks , Is there any clear doc or tutorial freeswitch with mongodb realtime

**Comment by zeflq** [comment]
if you mean load FS from mongoDB this why i started this tiny lib.i didn't found enough doc
